---
# this file contains main list of tasks to be executed by the elm role
# tasks file for elm-role
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"
  with_items: "{{ elm_dependencies }}"
  tags:
    - configuration
