---
- name: add elm and compile it from source
  shell: wget "https://github.com/elm/compiler/releases/download/0.19.0/binaries-for-linux.tar.gz"
  args:
    creates: /etc/apt/source.list.d/elmsourse.list
  tags:
    - confuguration

- name: unpack elm binaries
  shell: tar xzf binaries-for-linux.tar.gz
  args:
    creates: /etc/apt/source.list.d/elmunpacksource.list
  tags:
    - confuguration

- name: remove elm binaries
  shell: rm -rf binaries-for-linux.tar.gz

- name: move elm to bin
  shell: mv elm /usr/local/bin/
  tags:
    - configuration

- name: setup elm project
  shell: yes | elm init
  args:
    chdir: "{{ project_path }}"
